# Generated by Django 3.2.9 on 2021-11-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='contactemail',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contactnumber',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='home',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='page',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='socialplatform',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='whoweare',
            name='update_at',
        ),
        migrations.AddField(
            model_name='contactnumber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='home',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='socialplatform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
