# Generated by Django 3.2.5 on 2021-08-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_bits_school'),
        ('accounts', '0002_customuser_is_verified'),
    ]

    operations = [
    ]
