# Generated by Django 3.2.5 on 2021-07-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_bits_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitsschool',
            options={'verbose_name_plural': 'Bits Schools'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
