# Generated by Django 3.2.5 on 2021-08-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_extra_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bits_school',
        ),
    ]
