# Generated by Django 3.2.5 on 2021-08-10 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_bits_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bits_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bitsschool'),
        ),
    ]
